### ISSUE TITLE
NPE on Ubuntu 64

### ISSUE THREAD

**Issue by riwsky** [thickey/lein-nevam#2]
trying to use lein nevam from ubuntu 12.04:

```
> $ lein version
Leiningen 2.0.0 on Java 1.6.0_27 OpenJDK 64-Bit Server VM

> $ lein nevam
java.lang.NullPointerException
    at clojure.core$with_meta.invoke(core.clj:211)
    at clojure.data.zip$mapcat_chain.invoke(zip.clj:86)
    at clojure.data.zip.xml$xml__GT_.doInvoke(xml.clj:74)
    at clojure.lang.RestFn.applyTo(RestFn.java:139)
    at clojure.core$apply.invoke(core.clj:603)
    at clojure.data.zip.xml$xml1__GT_.doInvoke(xml.clj:82)
    at clojure.lang.RestFn.invoke(RestFn.java:460)
    at leiningen.nevam.pom2proj$deploy_repositories.invoke(pom2proj.clj:68)
    at leiningen.nevam.pom2proj$lein_project_info.invoke(pom2proj.clj:83)
    at leiningen.nevam.pom2proj$process_pom.invoke(pom2proj.clj:125)
    at leiningen.nevam$nevam.doInvoke(nevam.clj:14)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at clojure.lang.Var.invoke(Var.java:415)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.core$apply.invoke(core.clj:603)
    at leiningen.core.main$resolve_task$fn__1606.doInvoke(main.clj:132)
    at clojure.lang.RestFn.invoke(RestFn.java:410)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:603)
    at leiningen.core.main$apply_task.invoke(main.clj:167)
    at leiningen.core.main$_main$fn__1665.invoke(main.clj:237)
    at leiningen.core.main$_main.doInvoke(main.clj:221)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:415)
    at clojure.lang.AFn.applyToHelper(AFn.java:161)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.core$apply.invoke(core.clj:601)
    at clojure.main$main_opt.invoke(main.clj:324)
    at clojure.main$main.doInvoke(main.clj:427)
    at clojure.lang.RestFn.invoke(RestFn.java:436)
    at clojure.lang.Var.invoke(Var.java:423)
    at clojure.lang.AFn.applyToHelper(AFn.java:167)
    at clojure.lang.Var.applyTo(Var.java:532)
    at clojure.main.main(main.java:37)
```

**Comment by maacl** [comment]
I am also getting a NPE on Ubuntu 16.06 using `[lein-nevam "0.1.2"]`

Here is a link to the [pom.xml](https://github.com/DaisyDiff/DaisyDiff/blob/master/pom.xml).

``` l
lein -version
Leiningen 2.6.1 on Java 1.8.0_91 OpenJDK 64-Bit Server VM
```

```
➜  DaisyDiff git:(master) ✗ lein nevam -v
java.lang.NullPointerException: null
 at clojure.core$with_meta__4375.invokeStatic (core.clj:218)
    clojure.core/with_meta (core.clj:217)
    clojure.data.zip$mapcat_chain.invokeStatic (zip.clj:86)
    clojure.data.zip$mapcat_chain.invoke (zip.clj:81)
    clojure.data.zip.xml$xml__GT_.invokeStatic (xml.clj:74)
    clojure.data.zip.xml$xml__GT_.doInvoke (xml.clj:56)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    clojure.data.zip.xml$xml1__GT_.invokeStatic (xml.clj:82)
    clojure.data.zip.xml$xml1__GT_.doInvoke (xml.clj:79)
    clojure.lang.RestFn.invoke (RestFn.java:439)
    leiningen.nevam.pom2proj$attr_map$fn__711.invoke (pom2proj.clj:17)
    clojure.lang.PersistentVector.reduce (PersistentVector.java:341)
    clojure.core$reduce.invokeStatic (core.clj:6544)
    clojure.core$reduce.invoke (core.clj:6527)
    leiningen.nevam.pom2proj$attr_map.invokeStatic (pom2proj.clj:16)
    leiningen.nevam.pom2proj$attr_map.invoke (pom2proj.clj:14)
    leiningen.nevam.pom2proj$parent.invokeStatic (pom2proj.clj:52)
    leiningen.nevam.pom2proj$parent.invoke (pom2proj.clj:50)
    leiningen.nevam.pom2proj$lein_project_info.invokeStatic (pom2proj.clj:83)
    leiningen.nevam.pom2proj$lein_project_info.invoke (pom2proj.clj:78)
    leiningen.nevam.pom2proj$process_pom.invokeStatic (pom2proj.clj:131)
    leiningen.nevam.pom2proj$process_pom.invoke (pom2proj.clj:128)
    leiningen.nevam$nevam.invokeStatic (nevam.clj:14)
    leiningen.nevam$nevam.doInvoke (nevam.clj:5)
    clojure.lang.RestFn.invoke (RestFn.java:423)
    clojure.lang.Var.invoke (Var.java:383)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$partial_task$fn__5829.doInvoke (main.clj:272)
    clojure.lang.RestFn.applyTo (RestFn.java:139)
    clojure.lang.AFunction$1.doInvoke (AFunction.java:29)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:648)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.main$apply_task.invokeStatic (main.clj:322)
    leiningen.core.main$apply_task.invoke (main.clj:308)
    leiningen.core.main$resolve_and_apply.invokeStatic (main.clj:328)
    leiningen.core.main$resolve_and_apply.invoke (main.clj:324)
    leiningen.core.main$_main$fn__5895.invoke (main.clj:401)
    leiningen.core.main$_main.invokeStatic (main.clj:394)
    leiningen.core.main$_main.doInvoke (main.clj:391)
    clojure.lang.RestFn.invoke (RestFn.java:421)
    clojure.lang.Var.invoke (Var.java:383)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.main$main_opt.invokeStatic (main.clj:314)
    clojure.main$main_opt.invoke (main.clj:310)
    clojure.main$main.invokeStatic (main.clj:421)
    clojure.main$main.doInvoke (main.clj:384)
    clojure.lang.RestFn.invoke (RestFn.java:457)
    clojure.lang.Var.invoke (Var.java:394)
    clojure.lang.AFn.applyToHelper (AFn.java:165)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
```
